### PR TITLE
Support secure sockets when on https

### LINKED ISSUE #108: Allow Secure Web Sockets
Our hapi server is configured for https and we get the following error when attempting to view the debug console: 

Uncaught SecurityError: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.

Are there any plans to support secure web sockets?

### PR DESCRIPTION
**Pull request by geek**
Fixes #108

### CODE REVIEW

**Comment by osukaa** [comment]
Could you update your branch to check if it fails?

**Comment by geek** [comment]
@osukaa the io.js build is failing because it looks like io.js can't be installed on the travis machine :/

**Comment by osukaa** [comment]
I was checking that a few days ago, I was looking through Travis docs but it seems it only uses the latest iojs stable release. :s

**Comment by gergoerdosi** [comment]
It's possible to specify the version: `- 'iojs-v2.5.0'`

**Comment by lloydbenson** [comment]
since hapi doesnt support iojs and had it recently removed and tv is a plugin specific to hapi, you can likely just remove iojs all together.

**Comment by osukaa** [comment]
I'll be merging this to close https://github.com/hapijs/tv/issues/108

**Comment by joaquimserafim** [comment]
Hey guys,

any news about this PR?

take care

**Comment by osukaa** [comment]
Maybe @geek can update the PR for TV v5

**Comment by joaquimserafim** [comment]
:+1:  thanks

**Comment by osukaa** [comment]
@joaquimserafim I'll publish 5.0.1 in a couple of hours. :)

**Comment by joaquimserafim** [comment]
great :)

**Comment by osukaa** [comment]
@joaquimserafim done

**Comment by joaquimserafim** [comment]
awesome :+1: 
thanks a lot mate!

take care

**Pull request merged**
